### PR TITLE
Add picture of UFO Galaxy from NASA

### PR DESCRIPTION
**Pull request by win8linux**
## Description

Picture from the Hubble Space Telescope of spiral galaxy NGC 2683 seen almost edge-on, giving it the shape of a classic science fiction spaceship. Hence, the nickname of "*UFO Galaxy*" given to it by astronomers.

### Image Information

- Author: NASA Goddard
- License: Public Domain
- Source: [Webpage](https://images.nasa.gov/details-GSFC_20171208_Archive_e001757), [Original image](https://images-assets.nasa.gov/image/GSFC_20171208_Archive_e001757/GSFC_20171208_Archive_e001757~orig.jpg)

Source image has been downscaled to 4,169 × 2,160 size.

### Submitter Checklist

- [x] Submitter has reviewed the Image Requirements
- [x] Squashed commits with `git rebase -i` (if needed)
- [x] Updated the respective `meson.build` and `xml.in` files

### CODE REVIEW

**Comment by win8linux** [comment]
I was originally planning to crop the image to a 16:9 ratio, then downsize it to 3840x2160. However, it turns out that the source image works very well will almost every aspect ratio including more extreme widescreen formats. It was decided to crop the image to a 2:1 ratio, as it preserves the suitability of the image to most other aspect ratios the best.

**Review by JoshStrobl — COMMENTED** [review]
Not sure we need a bunch of submissions about space / shots from space. I'd rather not pollute budgie-backgrounds with many of them.

**Comment by win8linux** [comment]
This is prolly one of the space background Para that should be considered, due to its flexibility with most screen aspect ratios.

**Comment by JoshStrobl** [comment]
> This is prolly one of the space background PRs that should be considered, due to its flexibility with most screen aspect ratios.

While true, the photo is exceedingly large (both in terms of resolution and size). Could do with some downscaling and slight compression, otherwise the git repo size itself is going to bloat substantially. It's fine otherwise.

**Comment by win8linux** [comment]
> Could do with some downscaling and slight compression, otherwise the git repo size itself is going to bloat substantially.

Replaced image with the source image downscaled to 4,169 × 2,160 size at 80% quality. Is it ok?

**Review by JoshStrobl — APPROVED** [review]
Perfect, thanks!

**Pull request merged**
