### PR TITLE
Cull a bunch of backgrounds

### PR DESCRIPTION
**Pull request by JoshStrobl**
Now that we have a bunch more images, with the likelihood of a small portion being proposed to be incrementally added over time (instead of in one go) with others being swapped out, let's get the cleanup out of the way now so we can restore budgie-backgrounds to a sane size.

### CODE REVIEW

**Comment by win8linux** [comment]
Would also suggest removing the following backgrounds as well:
* Casa Mila (looks overly filtered)
* Oakland Zoo Otters (desktop text less readable at bottom)
* Motherboard Circuits (already going to be removed however an upcoming submission may replace it)
* Ocean Waves (less readable desktop text at top)

Only existing backgrounds proposed for removal which I'd vouch strongly for retaining would be:
* Orange Hallway (eye-popping, desktop text very readable on it, symmetrically sound)
* Saturnian Profile (cleanest space-related background we have, desktop text very readable on it, symmetrically sound)
* Kitten on Lawn (personal preference towards cats aside, I have seen some positive feedback regarding its inclusion)

**Comment by JoshStrobl** [comment]
Appreciate the feedback but the PR review is targeted at @serebit as basically a "make sure I don't remove something you are super passionate about". If he hadn't asked, I would've just pulled the trigger on the removals immediately. I'm removing wallpapers even I like because frankly if I kept anything in that's "nice enough" then nothing would end up being removed.

- Casa Mila: Yea that could be removed. Thoughts from @serebit would be nice.
- Desktop text "on bottom" or "on top" isn't something I think we need to control for or go out of our way to control for. You may only be impacted if you use desktop icons (a default that I think most just turn off) or have a transparent panel and IMO in both cases the user is gonna control for that.
- Space wallpapers are a dime a dozen. I am doubtful the majority of users would go out of their way to set it.
- Motherboard circuits probably doesn't need a replacement. Nobody is gonna be setting that as a wallpaper.
- Kitten on lawn: Nothing special about it. It's a cat.
- DOF on the canyon wren is fine IMO, the point is to draw attention to the bird not the rocks. Having everything in focus means nothing is really in focus.

**Comment by win8linux** [comment]
The desktop text readability checks could be skipped true, as they're mainly meant as another possible metric to consider with backgrounds. More of a soft criteria really, instead of a hard requirement.

**Comment by serebit** [comment]
We keep Saturn. Otherwise LGTM.

**Review by serebit — CHANGES_REQUESTED** [review]
We're keeping Saturn. LGTM otherwise.

**Comment by JoshStrobl** [comment]
Restored Saturn background.

**Review by serebit — APPROVED** [review]

**Pull request merged**
