### PR TITLE
Add Saturnian Profile background

### PR DESCRIPTION
**Pull request by win8linux**
## Description

An image mosaic from NASA's Cassini spacecraft showing Saturn two days before it plunged into the planet's atmosphere. The brightened version from the source is used as a base, then the moons were removed to match the original version's focus on Saturn.

### Image Information

- Author: NASA/JPL-Caltech/Space Science Institute/Julius Enriquez
- License: Public Domain
- Source: [Webpage](https://www.jpl.nasa.gov/images/pia17218-a-farewell-to-saturn), [Original](https://d2pn8kiwq2w21t.cloudfront.net/original_images/jpegPIA17218.jpg), [Brightened](https://photojournal.jpl.nasa.gov/figures/PIA17218_fig1.jpg)

### Submitter Checklist

- [x] Submitter has reviewed the Image Requirements
- [x] Squashed commits with `git rebase -i` (if needed)
- [x] Updated the respective `meson.build` and `xml.in` files

### CODE REVIEW

**Review by JoshStrobl — COMMENTED** [review]
Not sure we need a bunch of submissions about space / shots from space. I'd rather not pollute budgie-backgrounds with many of them.

**Comment by serebit** [comment]
I'm in favor of space shots, but I do think we should be more selective with which ones we add. I'll go through the submitted ones later and see if any strike my fancy.

**Comment by win8linux** [comment]
Among the unmerged space background PRs, this is prolly the one I'll vouch for the most. It is among the best NASA has to offer (out of their entire corpus of space imagery) which wasn't processed by an external party that wanted a different license from CC0/Public Domain.

**Review by JoshStrobl — APPROVED** [review]
Comparing to the other photos submitted, this is probably one of the better selected. I appreciate the use of the brightened version since you lose out on so much detail of the rings from the shadow of Saturn.

So going to be approving it.

**Review by serebit — APPROVED** [review]

**Pull request merged**
